### ISSUE TITLE
安装后报错500

### ISSUE THREAD

**Issue by zhheo** [halo-dev/theme-starter#2]
<img width="798" alt="Snipaste_2024-05-07_19-32-44" src="https://github.com/halo-dev/theme-starter/assets/33177975/7e7fd2f8-e67b-49af-aed4-770af3c1a3c5">
<img width="814" alt="Snipaste_2024-05-07_19-32-53" src="https://github.com/halo-dev/theme-starter/assets/33177975/c79aea7f-6cf4-4163-997c-16262bdf17c3">
<img width="833" alt="Snipaste_2024-05-07_19-32-59" src="https://github.com/halo-dev/theme-starter/assets/33177975/ba74d5ab-b809-4640-9fac-cf3ff271c397">

安装后主题也打不开，是安装姿势不对么

**Comment by ruibaby** [comment]
建议提供复现步骤和日志，在我这边并未复现这个问题。

**Comment by zhheo** [comment]
解决了，
metadata:
  name: theme-starter
name里面的横线去掉就可以用了。比如我改成了themestarter就可以了

困困鱼有横线没问题可以正常运行，我也不知道什么情况触发的。既然解决了就先搁置了。
macos + docker部署环境 halo 2.12

**Comment by ruibaby** [comment]
> 解决了， metadata: name: theme-starter name里面的横线去掉就可以用了。比如我改成了themestarter就可以了
> 
> 困困鱼有横线没问题可以正常运行，我也不知道什么情况触发的。既然解决了就先搁置了。 macos + docker部署环境 halo 2.12

应该没有这个限制，只是目前在主题开发环境下，metadata.name 需要和主题文件夹保持一致，否则就会有资源加载的问题。生产环境下安装主题时，会将主题文件夹自动命名为 metadata.name，所以不会有这个问题。

**Comment by zhheo** [comment]
原来如此，文件夹名称不一致的原因，非常感谢！
